force-app/main/default/objects/ActionConfig__mdt/ActionConfig__mdt.object-meta.xml
<CustomObject>
    <label>Action Config</label>
    <pluralLabel>Action Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ActionConfig__mdt/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <label>Action Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActionConfig__mdt/fields/HandlerApexClass__c.field-meta.xml
<CustomField>
    <fullName>HandlerApexClass__c</fullName>
    <label>Handler Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MonitorRequest__c/MonitorRequest__c.object-meta.xml
<CustomObject>
    <label>Monitor Request</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Monitor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitor Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonitorRequest__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <label>Action Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AbstractActionChecker.cls
public with sharing abstract class AbstractActionChecker {
    
    @TestVisible
    private static AbstractActionChecker mockedChecker;

    protected MonitorRequest__c request;

    public interface Checkable {
        Boolean isFinished();
    }

    public abstract Checkable checkStatus();
    protected virtual void setContext(MonitorRequest__c request) {
        this.request = request;
    }
    
    public static AbstractActionChecker getInstance(MonitorRequest__c request) {

        if (mockedChecker != null) return mockedChecker;

        ActionConfig__mdt[] configs = [SELECT HandlerApexClass__c 
                                        FROM ActionConfig__mdt 
                                        WHERE ActionType__c = :request.ActionType__c];

        if (configs.isEmpty()) {
            throw new ActionCheckerException('No checker configured for action ' + request.ActionType__c);
        }

        Type checkerType = Type.forName(configs[0].HandlerApexClass__c);

        if (!AbstractActionChecker.class.isAssignableFrom(checkerType)) {
            throw new ActionCheckerException(configs[0].HandlerApexClass__c + ' must extend ' + AbstractActionChecker.class.getName());
        }

        AbstractActionChecker instance = (AbstractActionChecker)checkerType.newInstance();
        instance.setContext(request);

        return instance;
    }

    public class ActionCheckerException extends Exception {}
}