force-app/main/default/objects/MonitorRequest__c/MonitorRequest__c.object-meta.xml
<CustomObject>
    <label>Monitor Request</label>
    <nameField>
        <displayFormat>MR-{00000}</displayFormat>
        <label>Monitor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitor Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonitorRequest__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotifierConfig__mdt/NotifierConfig__mdt.object-meta.xml
<CustomObject>
    <label>Notifier Config</label>
    <pluralLabel>Notifier Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/NotifierConfig__mdt/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <label>Named Credential</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotifierConfig__mdt/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github</fullName>
                <default>true</default>
                <label>Github</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AbstractMonitorNotifier.cls
public with sharing abstract class AbstractMonitorNotifier {
    
    @TestVisible
    private static AbstractMonitorNotifier mockedNotifier;

    protected MonitorRequest__c request;
    protected NotifierConfig__mdt config;

    public abstract void notify();
    
    protected virtual void setContext(MonitorRequest__c request, NotifierConfig__mdt config) {
        this.request = request;
        this.config = config;
    }

    public static AbstractMonitorNotifier getInstance(MonitorRequest__c request) {

        if (mockedNotifier != null) return mockedNotifier;

        NotifierConfig__mdt[] configs = [SELECT HandlerApexClass__c, NamedCredential__c
                                            FROM NotifierConfig__mdt 
                                            WHERE Provider__c = :request.Provider__c];

        if (configs.isEmpty()) {
            throw new MonitorNotifierException('No notifier configured for provider ' + request.Provider__c);
        }

        Type notifierType = Type.forName(configs[0].HandlerApexClass__c);

        if (!AbstractMonitorNotifier.class.isAssignableFrom(notifierType)) {
            throw new MonitorNotifierException(configs[0].HandlerApexClass__c + ' must extend ' + AbstractMonitorNotifier.class.getName());
        }

        AbstractMonitorNotifier instance = (AbstractMonitorNotifier)notifierType.newInstance();
        instance.setContext(request, configs[0]);

        return instance;
    }

    public class MonitorNotifierException extends Exception {}
}